---
- name: Set Defaults  
  include_tasks: defaults.yaml

- name: OS Config 
  include_tasks: os.yaml
  
- name: Establish target rke2 Version 
  include_tasks: rke2-version.yaml

- name: Checking rke2 binary
  ansible.builtin.stat:
    path: "{{ rke2_bin_dir }}/rke2"
  register: rke2_binary

- name: Setup rke2 Config Files 
  include_tasks: config-files.yaml
    
- name: Install rke2
  include_tasks: install.yaml
  when: not rke2_binary.stat.exists or rke2_action == 'upgrade'

- name: Fire rke2
  include_tasks: fire-rke2.yaml