---
- name: Add rke2_api_hostname to /etc/hosts
  become: true 
  lineinfile: 
    path: /etc/hosts
    regexp: "^{{ rke2_api_ip }} {{ rke2_api_hostname }} {{ rke2_api_fqdn }}"
    line: "{{ rke2_api_ip }} {{ rke2_api_hostname }} {{ rke2_api_fqdn }}"
    state: present

- name: Add local-rke2.env file to server root homedir, for any local debugging
  become: true 
  copy: 
    src: local-rke2.env
    dest: /root/local-rke2.env
    owner: root 
    group: root 
    mode: 0700
