---
- name: Set Defaults  
  include_tasks: defaults.yaml

- name: OS Config 
  include_tasks: os.yaml
  
- name: Establish rke2 Version 
  include_tasks: rke2_version.yaml 

- name: Setup rke2 Config Files 
  include_tasks: config_files.yaml
  vars:
    rke2_token: "{{ lookup('community.general.random_string', length=8, special=false) }}"
  
- name: Install rke2
  include_tasks: install.yaml

- name: Start first server
  include_tasks: fire_rke2.yaml
  when: inventory_hostname == groups['servers'][0]
  run_once: true

- name: Fetch full node-token from first server (includes CA Hash)
  slurp:
    src: /var/lib/rancher/rke2/server/node-token
  register: node_token
  delegate_to: "{{ groups['servers'][0] }}"
  run_once: true
  become: true

- name: Set the full node-token as a variable
  set_fact:
    rke2_token: "{{ node_token.content | b64decode }}"    

- name: Update config.yaml
  include_tasks: config_files.yaml

- name: Start all servers
  include_tasks: fire_rke2.yaml
  when: rke2_role == 'server'

- name: Start all agents
  include_tasks: fire_rke2.yaml
  when: rke2_role == 'agent'

- name: Write local-path-provisioner Manifest
  ansible.builtin.template: 
    src: "local-path-provisioner.yaml.j2"
    dest: "{{ rke2_manifests_dir }}/local-path-provisioner.yaml"
    owner: root 
    group: root 
    mode: 0644
  when: rke2_local_storage and rke2_role == 'server'
  become: true 
