---
- name: Set Defaults  
  include_tasks: defaults.yaml

- name: OS Config 
  include_tasks: os.yaml
  
- name: Establish target rke2 Version 
  include_tasks: rke2_version.yaml

- name: Checking rke2 binary
  ansible.builtin.stat:
    path: "{{ rke2_bin_dir }}/rke2"
  register: rke2_binary

- block:
  - name: Setup rke2 Config Files 
    include_tasks: config_files.yaml
    
  - name: Install rke2
    include_tasks: install.yaml
  when: not rke2_binary.stat.exists or rke2_action == 'upgrade'

- name: Start all servers
  include_tasks: fire_rke2.yaml
  when: inventory_hostname in groups['servers']

- name: Start all agents
  include_tasks: fire_rke2.yaml
  when: inventory_hostname not in groups['servers']

- name: Write local-path-provisioner Manifest
  ansible.builtin.template: 
    src: "manifests/local-path-provisioner.yaml.j2"
    dest: "{{ rke2_manifests_dir }}"
    owner: root 
    group: root 
    mode: 0644
  when: rke2_local_storage and rke2_role == 'server'
  become: true 

- name: Write rke2-ingress-nginx-config Manifest
  ansible.builtin.template: 
    src: "manifests/rke2-ingress-nginx-config.yaml.j2"
    dest: "{{ rke2_manifests_dir }}"
    owner: root 
    group: root 
    mode: 0644
  when: rke2_nginx_tcp_services is defined or rke2_nginx_udp_services is defined
  become: true 
