---
- name: Ensure rke2_manifests_dir exists
  ansible.builtin.file:
    name: "{{ rke2_manifests_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

### local-path-provisioner ###
# selinux policy config is in os.yaml.  longhorn and local-storage share the same policy
- block:
  - name: Ensure rke2_local_storage_path exists
    ansible.builtin.file:
      name: "{{ rke2_local_storage_path }}"
      state: directory
      owner: root
      group: root
      mode: 0777

  - name: Write local-path-provisioner Manifest
    ansible.builtin.template: 
      src: "manifests/local-path-provisioner.yaml.j2"
      dest: "{{ rke2_manifests_dir }}/local-path-provisioner.yaml"
      owner: root 
      group: root 
      mode: 0644
    when: rke2_role == 'server'
  become: true 
  when: rke2_local_storage | default(false) | bool

### ingress-nginx helm config ###
# currently only used for tcp/udp services
- name: Write rke2-ingress-nginx-config Manifest
  ansible.builtin.template: 
    src: "manifests/rke2-ingress-nginx-config.yaml.j2"
    dest: "{{ rke2_manifests_dir }}/rke2-ingress-nginx-config.yaml"
    owner: root 
    group: root 
    mode: 0644
  become: true
  when: rke2_nginx_tcp_services is defined or rke2_nginx_udp_services is defined