---
- name: fire rke2
  block:
  - name: rke2-server systemd service
    ansible.builtin.systemd:
      name: "rke2-server"
      state: "{{ 'restarted' if rke2_action == 'upgrade' else 'started' }}"
      enabled: true
      daemon_reload: true
      no_block: true
    when: rke2_role == 'server'
    become: true

  - name: Wait for port 6443
    ansible.builtin.wait_for:
      port: 6443
      delay: 60
      timeout: 600
    when: 
    - rke2_role == 'server'
    - rke2_action == 'upgrade'

  - name: Wait for rke2 server nodes to be Ready
    ansible.builtin.shell: "/var/lib/rancher/rke2/bin/kubectl --kubeconfig {{ rke2_server_kubeconfig }} get nodes | grep {{ ansible_hostname }}"
    args:
      executable: /bin/bash
    changed_when: false 
    register: node_ready
    until: '" Ready " in node_ready.stdout'
    retries: 10
    delay: 30
    become: true
    when: rke2_role == 'server'

  - name: rke2-agent systemd service
    ansible.builtin.systemd:
      name: "rke2-agent"
      state: "{{ 'restarted' if rke2_action == 'upgrade' else 'started' }}"
      enabled: true
      daemon_reload: true
      no_block: true
    when: rke2_role != 'server'
    become: true
