---
- name: Include common tasks
  include_tasks: common.yaml
  when: rke2_action in ['upgrade', 'install']

# can add install.yaml and/or upgrade.yaml file if there is ever a need to

- name: Include teardown tasks
  include_tasks: teardown.yaml
  when: rke2_action == 'teardown'
