---
### rke2_role ###
- name: Default rke2_role to server if not provided
  set_fact: 
    rke2_role: server
  when: rke2_role is not defined 
  
- name: Include common tasks
  include_tasks: common.yaml
  when: rke2_action in ['upgrade', 'install']

# can add install.yaml and/or upgrade.yaml file if there is ever a need to

# need restart.yaml here too

- name: Include teardown tasks
  include_tasks: teardown.yaml
  when: rke2_action == 'teardown'
