---
### rke2_role ###
# this is a hostvar that we need to set.  it should come from inventory
- name: Default rke2_role to server if not provided
  set_fact: 
    rke2_role: server
  when: rke2_role is not defined 

# install/upgrade most common path for this role to take
- name: Include common tasks for upgrades and installs
  include_tasks: common.yaml
  when: rke2_action in ['upgrade', 'install']

- name: Include teardown tasks
  include_tasks: teardown.yaml
  when: rke2_action == 'teardown'
