---
- block:
  - name: Get index of rke2 release channels
    ansible.builtin.uri: 
      url: https://update.rke2.io/v1-release/channels
    register: msg

  - name: Get latest version of the requested rke2_channel  
    set_fact:
      latest_rke2_version: "{{ msg.json.data | json_query(query) }}"
    vars: 
      query: "[? name==`{{ rke2_channel }}`].latest"

  - debug: >
      msg="Latest available version in rke2_channel {{ rke2_channel }} is: {{ latest_rke2_version[0] }}"

  - name: Set rk2_version if a specific version was not provided
    set_fact: 
      rke2_version: "{{ latest_rke2_version[0] }}"
    when: rke2_version is undefined

  - name: Set rk2_version_plain
    set_fact: 
      rke2_version_plain: "{{ rke2_version | replace('+', '') }}"

  - debug: >
      msg="We are installing: {{ rke2_version }}.  rke2_version_plain={{ rke2_version_plain }}"
  tags: upgrade