---
- name: Determine current installed version, if any
  ansible.builtin.command: /usr/local/bin/rke2 --version
  register: rke2_version_output
  changed_when: false 
  failed_when: false
  tags: upgrade 

- debug:
    msg: "Current installed rke2 version is: {{ rke2_version_output.stdout }}"
  when: rke2_version_output.rc == 0
  tags: upgrade

- block:
  - name: Create rke2 assets dir
    ansible.builtin.file:
      path: "/opt/rke2/{{ rke2_version_plain }}"
      state: directory
      owner: root
      group: root 
      mode: 0755 

  - name: Download rke2 checksums
    ansible.builtin.get_url:
      url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version | urlencode }}/sha256sum-amd64.txt"
      dest: "/opt/rke2/{{ rke2_version_plain }}"
      owner: root
      group: root
      mode: 0644

  - name: Read rke2 checksums
    ansible.builtin.slurp:
      src: "/opt/rke2/{{ rke2_version_plain }}/sha256sum-amd64.txt"
    register: checksums 
  - debug: var=checksums

  - name: Register rke2 binary checksum
    set_fact: 
      rke2_bin_checksum: "{{ checksums['content'] | b64decode | split('\n') | select('match', '.*rke2.linux-amd64$') | join() | split(' ') | first }}"
  - debug: var=rke2_bin_checksum

  - name: Register rke2 images checksum
    set_fact: 
      rke2_images_checksum: "{{ checksums['content'] | b64decode | split('\n') | select('match', '.*rke2-images.linux-amd64.tar.zst$') | join() | split(' ') | first }}"
  - debug: var=rke2_images_checksum

  - name: Download rke2 images
    ansible.builtin.get_url:
      url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version | urlencode }}/rke2-images.linux-amd64.tar.zst"
      dest: "/opt/rke2/{{ rke2_version_plain }}"
      owner: root
      group: root 
      mode: 0644
      checksum: "sha256:{{ rke2_images_checksum }}"
    register: images_archive 

  - name: Download rke2 binary
    ansible.builtin.get_url:
      url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version | urlencode }}/rke2.linux-amd64"
      dest: "/opt/rke2/{{ rke2_version_plain }}/rke2"
      owner: root
      group: root 
      mode: 0755
      checksum: "sha256:{{ rke2_bin_checksum }}"
    register: binary_file

  - name: Ensure rke2 images dir exists
    ansible.builtin.file:
      path: "{{ rke2_images_dir }}"
      state: directory
      owner: root 
      group: root 
      mode: 0755 

  - name: Move images archive to images dir  
    ansible.builtin.copy: 
      src: "{{ images_archive.dest }}"
      dest: "{{ rke2_images_dir }}/"
      owner: root 
      group: root 
      mode: 0644
      remote_src: true 

  - name: Move rke2 binary to /usr/local/bin   
    ansible.builtin.copy: 
      src: "{{ binary_file.dest }}"
      dest: "{{ rke2_bin_dir }}/rke2" 
      owner: root 
      group: root 
      mode: 0755 
      remote_src: true

  - name: Install rke2 service file 
    ansible.builtin.template:
      src: rke2.service.j2
      dest: "{{ rke2_systemd_dir }}/rke2-{{ rke2_role }}.service" 
      owner: root
      group: root 
      mode: 0644
  when: rke2_version_output.rc != 0 or (rke2_upgrade | default('false') | bool )
  become: true 
  tags: upgrade