---
- name: reboot
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    reboot_timeout: 600
    test_command: uptime
    pre_reboot_delay: 10
  become: true

- name: restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
  become: true

- name: restart systemd-sysctl
  ansible.builtin.systemd:
    name: systemd-sysctl
    state: restarted
  become: true

- name: restart iscsid
  ansible.builtin.systemd:
    name: iscsid
    state: restarted
  become: true

- name: selinux restorecon
  ansible.builtin.command:
    argv:
    - restorecon
    - -R
    - /var/lib
    - /var/lib/rancher
    - /etc/rancher
    - /usr/local/bin
  become: true 
  when: ansible_os_family | lower == "redhat"
