---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: "${MOLECULE_DISTRO:-ubuntu/jammy64}"
    memory: 4096
    provider:
      name: virtualbox
provisioner:
  name: ansible
  inventory:
    hosts:
      servers:
        hosts:
          instance
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - create
    - converge
    - destroy
