---
- block:
  - name: Install container-selinux package 
    package: container-selinux
    state: latest 

  - name: Download selinux RPM
    ansible.builtin.get_url:
      url: >
        "https://github.com/rancher/rke2-selinux/releases/download/{{ rke2_selinux_release }}/{{ rke2_selinux_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
      dest: /tmp/selinux.rpm

  - name: Install RPM (RHEL 7)
    ansible.builtin.yum:
      name: /tmp/selinux.rpm
      state: present
    when: ansible_distribution_major_version == '7'

  - name: Install RPM (RHEL 8)
    ansible.builtin.dnf:
      name: /tmp/selinux.rpm
      state: present
    when: ansible_distribution_major_version == '8'
  become: true 
  tags: os